export const metricDefinitions = Object.freeze({
  playerMaxKillStreak: {
    label: "Highest player kill streak",
    scope: "player",
    unit: "kills",
    source: "confirmed_self_kill_death_events",
    description: "Highest confirmed owner/player kill streak across rounds and activity segments. Self deaths and round/activity boundaries reset the streak.",
    caveat: "Server broadcast streaks for other players do not affect this value.",
  },
  observedBroadcastMaxKillStreak: {
    label: "Highest observed broadcast kill streak",
    scope: "observed_server_chat",
    unit: "kills",
    source: "server_broadcast_chat",
    description: "Highest kill-streak number observed in server chat broadcasts.",
    caveat: "This may belong to another player and must not be displayed as a personal best.",
  },
  maxStreak: {
    label: "Legacy observed broadcast streak",
    scope: "observed_server_chat",
    unit: "kills",
    source: "legacy_alias",
    description: "Deprecated alias for observedBroadcastMaxKillStreak.",
    deprecated: true,
  },
  bestWinStreak: {
    label: "Best win streak",
    scope: "formal_result_rounds",
    unit: "rounds",
    source: "round_results",
    description: "Best consecutive win run using the conservative break_unknown policy.",
    caveat: "The API also exposes skip_unknown under profile.streaks.win for users who choose to skip unknown/ambiguous rounds.",
  },
  currentWinStreak: {
    label: "Current win streak",
    scope: "formal_result_rounds",
    unit: "rounds",
    source: "round_results",
    description: "Current consecutive win run using the conservative break_unknown policy.",
  },
  winStreaks: {
    label: "Win streak policies",
    scope: "formal_result_rounds",
    unit: "rounds",
    source: "round_results",
    description: "Win streak summaries for break_unknown and skip_unknown policies. Loss always breaks; win increments; unknown/ambiguous either break or are skipped by policy.",
  },
  bedDestroys: {
    label: "All observed bed destroys",
    scope: "round_observed_events",
    unit: "events",
    source: "bed_destroy_events",
    description: "All bed-destroy events observed in a round or aggregate.",
  },
  selfBedDestroys: {
    label: "Player bed destroys (legacy)",
    scope: "player",
    unit: "events",
    source: "owner_bound_bed_destroy_events",
    description: "Compatibility field for beds destroyed by the owner/player.",
  },
  playerBedDestroys: {
    label: "Player bed destroys",
    scope: "player",
    unit: "events",
    source: "owner_bound_bed_destroy_events",
    description: "Recommended public field for beds destroyed by the owner/player. It equals selfBedDestroys.",
  },
  resultEligible: {
    label: "Result eligible",
    scope: "round",
    unit: "boolean",
    source: "round_builder",
    description: "False for non-win/loss continuous activity rows such as The Pit; result coverage and win rate exclude those rows.",
  },
  notApplicableResults: {
    label: "Non-result activity rows",
    scope: "round_aggregate",
    unit: "rounds",
    source: "activity_mirror_rows",
    description: "Rows mirrored from continuous activity segments with result not_applicable. They count for activity/KD/mode totals but not win/loss/unknown coverage.",
  },
  unknownResults: {
    label: "Unknown results",
    scope: "result_eligible_rounds",
    unit: "rounds",
    source: "round_results",
    description: "Reliable result-eligible rounds whose official result remains unknown.",
  },
  ambiguousResults: {
    label: "Ambiguous results",
    scope: "result_eligible_rounds",
    unit: "rounds",
    source: "round_results",
    description: "Reliable result-eligible rounds with conflicting win/loss evidence. This should stay zero in normal operation.",
  },
  rewardEvents: {
    label: "Activity reward prompts",
    scope: "activity",
    unit: "events",
    source: "explicit_activity_reward_chat",
    description: "Count of clear activity reward prompt events such as The Pit kill/assist rewards, gold pickups, free XP, death-streak rewards, or streak-point awards.",
    caveat: "This is an event count, not a gold/XP amount.",
  },
  goldEarned: {
    label: "The Pit gold earned",
    scope: "activity",
    unit: "gold",
    source: "explicit_pit_reward_chat",
    description: "Sum of explicit The Pit gold amounts parsed from player reward chat lines.",
    caveat: "This is not a full economy ledger; it only includes parsed explicit reward prompts and owner-bound bounty claims.",
  },
  xpEarned: {
    label: "The Pit XP earned",
    scope: "activity",
    unit: "xp",
    source: "explicit_pit_reward_chat",
    description: "Sum of explicit The Pit XP amounts parsed from player reward chat lines.",
    caveat: "This is not a full economy ledger; it only includes parsed explicit reward prompts.",
  },
  bountyClaims: {
    label: "The Pit bounty claims",
    scope: "player",
    unit: "events",
    source: "owner_bound_pit_bounty_claim_chat",
    description: "Count of The Pit bounty-claim broadcasts where the killer is confirmed to be the owner/player.",
    caveat: "Bounties placed on the player or claimed by other players stay diagnostic-only and do not increment this value.",
  },
  bountyGoldEarned: {
    label: "The Pit bounty gold earned",
    scope: "player",
    unit: "gold",
    source: "owner_bound_pit_bounty_claim_chat",
    description: "Gold earned from The Pit bounty-claim broadcasts where the killer is confirmed to be the owner/player.",
    caveat: "This is included in goldEarned; non-owner bounty broadcasts are excluded.",
  },
  activityGoldEarned: {
    label: "Activity gold earned",
    scope: "activity",
    unit: "gold",
    source: "activity_summary_alias",
    description: "Aggregate activity gold earned across continuous-mode activity segments.",
    caveat: "Currently this is sourced from parsed The Pit reward prompts and owner-bound bounty claims, not a full economy ledger.",
  },
  activityXpEarned: {
    label: "Activity XP earned",
    scope: "activity",
    unit: "xp",
    source: "activity_summary_alias",
    description: "Aggregate activity XP earned across continuous-mode activity segments.",
    caveat: "Currently this is sourced from parsed The Pit reward prompts, not a full economy ledger.",
  },
  activityBountyClaims: {
    label: "Activity bounty claims",
    scope: "player",
    unit: "events",
    source: "activity_summary_alias",
    description: "Aggregate owner-bound bounty claims across continuous-mode activity segments.",
  },
  activityBountyGoldEarned: {
    label: "Activity bounty gold earned",
    scope: "player",
    unit: "gold",
    source: "activity_summary_alias",
    description: "Aggregate gold earned from owner-bound bounty claims across continuous-mode activity segments.",
    caveat: "This is included in activityGoldEarned.",
  },
  pitGoldEarned: {
    label: "The Pit gold earned",
    scope: "activity",
    unit: "gold",
    source: "pit_activity_summary_alias",
    description: "The Pit aggregate gold earned from parsed reward prompts and owner-bound bounty claims.",
    caveat: "This is not a full economy ledger.",
  },
  pitXpEarned: {
    label: "The Pit XP earned",
    scope: "activity",
    unit: "xp",
    source: "pit_activity_summary_alias",
    description: "The Pit aggregate XP earned from parsed reward prompts.",
    caveat: "This is not a full economy ledger.",
  },
  pitBountyClaims: {
    label: "The Pit bounty claims",
    scope: "player",
    unit: "events",
    source: "pit_activity_summary_alias",
    description: "The Pit aggregate owner-bound bounty claim count.",
  },
  pitBountyGoldEarned: {
    label: "The Pit bounty gold earned",
    scope: "player",
    unit: "gold",
    source: "pit_activity_summary_alias",
    description: "The Pit aggregate gold earned from owner-bound bounty claims.",
    caveat: "This is included in pitGoldEarned.",
  },
  streakPoints: {
    label: "The Pit streak points",
    scope: "activity",
    unit: "points",
    source: "pit_streak_points_chat",
    description: "Sum of explicit The Pit Streak Points awards parsed from chat.",
  },
});

export function buildMetricDefinitions(keys = null) {
  if (!Array.isArray(keys) || keys.length === 0) return { ...metricDefinitions };
  const result = {};
  for (const key of keys) {
    if (metricDefinitions[key]) result[key] = metricDefinitions[key];
  }
  return result;
}
