import { readFile, stat } from "node:fs/promises";
import path from "node:path";
import { loadAppConfig, resolveConfigPath, resolveDataDir, resolveStoreDir } from "../src/config/appConfig.mjs";
import { buildDiagnosticsPackageManifest, buildPrivacyAudit } from "../src/diagnostics/privacyAudit.mjs";

const args = process.argv.slice(2);
const jsonOut = args.includes("--json");
const full = args.includes("--full");
const packageOut = args.includes("--package");
const privacySafeDiagnosticsForbiddenKeys = ["currentFile", "log", "logTail"];
const configContext = await loadAppConfig(readOption("--config") ?? undefined);
const checks = await buildDoctorChecks(configContext, { full });
const output = packageOut ? buildDoctorPackage(checks, { full, sensitiveValues: doctorSensitiveValues(configContext) }) : checks;

if (jsonOut || packageOut) {
  console.log(JSON.stringify(output, null, 2));
} else {
  printHumanSummary(checks);
}

async function buildDoctorChecks(context, options = {}) {
  const config = context.config;
  const reportPath = resolveConfigPath(context, config.outputs.report);
  const summaryPath = resolveConfigPath(context, config.outputs.summary);
  const dataDir = resolveDataDir(context);
  const storeDir = resolveStoreDir(context);
  const storeManifestPath = path.join(storeDir, "manifest.json");
  const refreshHistoryPath = resolveConfigPath(context, ".cache/refresh-history.json");
  const roots = await Promise.all(config.roots.map((root) => checkRoot(root, { full: options.full })));
  const outputs = {
    report: await checkJson(reportPath, options),
    summary: await checkJson(summaryPath, options),
    store: await checkStoreManifest(storeManifestPath, storeDir, options),
  };
  const cache = {
    parse: await checkFile(resolveConfigPath(context, config.cache.parse), options),
    chat: await checkFile(resolveConfigPath(context, config.cache.chat), options),
    chatLines: await checkFile(resolveConfigPath(context, config.cache.chatLines), options),
  };
  const checks = {
    schema: {
      name: "minecraft-log-observatory-doctor",
      version: 1,
    },
    generatedAt: new Date().toISOString(),
    privacy: options.full ? "full-local" : "privacy-safe",
    node: {
      version: process.version,
    },
    config: {
      path: redactMaybe(context.path, options),
      localPath: redactMaybe(context.localPath, options),
      localExists: context.localExists,
      layers: context.layers.map((layer) => ({
        ...layer,
        path: layer.path ? redactMaybe(layer.path, options) : layer.path,
      })),
      encoding: config.encoding,
      roots,
      rootCount: roots.length,
      ownerAliases: options.full ? config.owner.aliases ?? [] : redactList(config.owner.aliases ?? []),
      app: {
        dataDir: redactMaybe(dataDir, options),
        storeDir: redactMaybe(storeDir, options),
        skinProxyEnabled: config.app?.skinProxyEnabled !== false,
      },
    },
    outputs,
    cache,
    performance: await buildDoctorPerformance(refreshHistoryPath, { outputs, cache }),
  };

  checks.ready = checks.config.rootCount > 0
    && roots.every((root) => root.exists && root.type === "directory")
    && outputReady(checks.outputs.report)
    && outputReady(checks.outputs.summary)
    && outputReady(checks.outputs.store)
    && checks.outputs.store.filesReady !== false;
  checks.needsRefresh = !checks.outputs.report.exists
    || !checks.outputs.summary.exists
    || !checks.outputs.store.exists
    || Boolean(checks.outputs.report.jsonError)
    || Boolean(checks.outputs.summary.jsonError)
    || Boolean(checks.outputs.store.jsonError)
    || Boolean(checks.outputs.store.schemaError)
    || checks.outputs.store.filesReady === false;
  return checks;
}

function buildDoctorPackage(checks, options = {}) {
  const privacy = options.full ? "full-local" : "privacy-safe";
  const output = {
    schema: {
      name: "minecraft-log-observatory-doctor-package",
      version: 1,
    },
    generatedAt: new Date().toISOString(),
    privacy,
    manifest: buildDiagnosticsPackageManifest({
      kind: "doctor-package",
      privacy,
      sources: ["npm run doctor -- --package"],
      contents: [
        { key: "checks.config", description: "Config, local overlay, roots, owner aliases, and app data settings." },
        { key: "checks.outputs", description: "Report, summary, and split-store manifest readiness checks." },
        { key: "checks.cache", description: "Derived parse/chat cache file checks." },
        { key: "checks.performance", description: "Refresh-history performance baseline with successful-refresh phase durations." },
      ],
    }),
    containsRawLogs: false,
    containsRawChat: false,
    checks,
    notes: [
      "This package is generated by npm run doctor -- --package.",
      "It does not include raw Minecraft logs, chat lines, full reports, or split report-store rows.",
      options.full ? "Full-local mode may include local filesystem paths." : "Privacy-safe mode redacts local paths and configured owner aliases.",
    ],
  };
  output.privacyAudit = buildPrivacyAudit(output, {
    full: options.full,
    knownSensitiveValues: options.sensitiveValues ?? [],
    forbiddenKeys: privacySafeDiagnosticsForbiddenKeys,
  });
  return output;
}

function printHumanSummary(checks) {
  console.log(`Node: ${checks.node.version}`);
  console.log(`Privacy: ${checks.privacy}`);
  console.log(`Config: ${formatRedacted(checks.config.path)}`);
  console.log(`Local config: ${checks.config.localExists ? formatRedacted(checks.config.localPath) : `${formatRedacted(checks.config.localPath)} (not found)`}`);
  console.log(`Encoding: ${checks.config.encoding}`);
  console.table(checks.config.roots);
  console.table([
    { kind: "report", ...checks.outputs.report },
    { kind: "summary", ...checks.outputs.summary },
    { kind: "store", ...checks.outputs.store },
    { kind: "parseCache", ...checks.cache.parse },
    { kind: "chatCache", ...checks.cache.chat },
    { kind: "chatLinesCache", ...checks.cache.chatLines },
  ]);
  console.log(`Ready: ${checks.ready ? "yes" : "no"}`);
  console.log(`Needs refresh: ${checks.needsRefresh ? "yes" : "no"}`);
}

function readOption(name) {
  const index = args.indexOf(name);
  return index >= 0 ? args[index + 1] : null;
}

function doctorSensitiveValues(context) {
  const config = context.config;
  return [
    context.path,
    context.localPath,
    resolveDataDir(context),
    resolveStoreDir(context),
    resolveConfigPath(context, config.outputs.report),
    resolveConfigPath(context, config.outputs.summary),
    resolveConfigPath(context, ".cache/refresh-history.json"),
    resolveConfigPath(context, config.cache.parse),
    resolveConfigPath(context, config.cache.chat),
    resolveConfigPath(context, config.cache.chatLines),
    ...(config.roots ?? []),
    ...(config.owner?.aliases ?? []),
    ...(config.owner?.displayName && config.owner.displayName !== "Owner" ? [config.owner.displayName] : []),
  ].filter(Boolean);
}

async function checkRoot(rootPath, options) {
  const result = await checkFile(rootPath, options);
  return {
    root: redactMaybe(rootPath, options),
    exists: result.exists,
    type: result.type,
    sizeMb: result.sizeMb,
    modifiedAt: result.modifiedAt,
  };
}

async function checkJson(filePath, options) {
  const result = await checkFile(filePath, options);
  if (!result.exists) return result;
  try {
    const data = JSON.parse(await readFile(filePath, "utf8"));
    return {
      ...result,
      schema: data.schema ?? null,
      generatedAt: data.generatedAt ?? null,
      reportGeneratedAt: data.reportGeneratedAt ?? null,
    };
  } catch (error) {
    return {
      ...result,
      jsonError: error.message,
    };
  }
}

async function checkStoreManifest(filePath, storeDir, options) {
  const result = await checkFile(filePath, options);
  if (!result.exists) return result;
  let data;
  try {
    data = JSON.parse(await readFile(filePath, "utf8"));
  } catch (error) {
    return {
      ...result,
      jsonError: error.message,
    };
  }

  const output = {
    ...result,
    schema: data.schema ?? null,
    generatedAt: data.generatedAt ?? null,
    reportGeneratedAt: data.reportGeneratedAt ?? null,
  };
  const validation = validateStoreManifestForDoctor(data);
  if (!validation.ok) {
    return {
      ...output,
      schemaError: validation.message,
      schemaErrorReason: validation.reason,
      filesReady: false,
      missingFiles: [],
    };
  }

  const missingFiles = [];
  const files = [];
  const resolvedStoreDir = path.resolve(storeDir);
  for (const [name, fileName] of Object.entries(data.files ?? {})) {
    const filePathForEntry = path.resolve(resolvedStoreDir, fileName);
    if (!isSameOrInside(filePathForEntry, resolvedStoreDir)) {
      missingFiles.push({ name, file: fileName, reason: "outside_store_dir" });
      files.push({ name, file: fileName, kind: fileName.endsWith(".jsonl") ? "jsonl" : "json", exists: false, bytes: null, rows: null });
      continue;
    }
    const file = await checkFile(filePathForEntry, { ...options, full: true });
    const jsonl = fileName.endsWith(".jsonl");
    files.push({
      name,
      file: fileName,
      kind: jsonl ? "jsonl" : "json",
      exists: Boolean(file.exists && file.type === "file"),
      bytes: file.exists && file.type === "file" ? file.bytes : null,
      rows: jsonl && Number.isFinite(data.counts?.[name]) ? data.counts[name] : null,
    });
    if (!file.exists || file.type !== "file") {
      missingFiles.push({ name, file: fileName, reason: "missing" });
    }
  }

  const existingBytes = files.map((file) => file.bytes).filter(Number.isFinite);
  const jsonlRows = files.map((file) => file.rows).filter(Number.isFinite);
  return {
    ...output,
    declaredFiles: Object.keys(data.files ?? {}).length,
    filesReady: missingFiles.length === 0,
    missingFiles,
    totalBytes: existingBytes.length ? existingBytes.reduce((total, bytes) => total + bytes, 0) : null,
    totalJsonlRows: jsonlRows.length ? jsonlRows.reduce((total, rows) => total + rows, 0) : null,
    jsonlTables: files.filter((file) => file.kind === "jsonl").length,
    largestFiles: [...files]
      .filter((file) => Number.isFinite(file.bytes))
      .sort((left, right) => right.bytes - left.bytes || left.name.localeCompare(right.name))
      .slice(0, 10),
    tables: files
      .filter((file) => file.kind === "jsonl")
      .sort((left, right) => (right.rows ?? -1) - (left.rows ?? -1) || (right.bytes ?? -1) - (left.bytes ?? -1) || left.name.localeCompare(right.name)),
  };
}

async function buildDoctorPerformance(refreshHistoryPath, checks = {}) {
  const history = await readDoctorRefreshHistory(refreshHistoryPath);
  const items = history.items;
  const baseline = buildDoctorPerformanceBaseline(items, history.warning);
  const store = buildDoctorStorePerformance(checks.outputs?.store ?? {});
  const cache = buildDoctorCachePerformance(checks.cache ?? {});
  return {
    refreshHistory: {
      total: items.length,
      warning: history.warning,
      summary: summarizeDoctorRefreshHistory(items),
      latest: publicDoctorRefreshHistoryItem(items[0]),
    },
    warnings: history.warning ? [history.warning] : [],
    baseline,
    store,
    cache,
    recommendations: buildDoctorPerformanceRecommendations({
      baseline,
      store,
      cache,
      historyWarning: history.warning,
      needsRefresh: doctorPerformanceNeedsRefresh(checks),
    }),
  };
}

function doctorPerformanceNeedsRefresh(checks = {}) {
  const outputs = checks.outputs ?? {};
  return !outputs.report?.exists
    || !outputs.summary?.exists
    || !outputs.store?.exists
    || Boolean(outputs.report?.jsonError)
    || Boolean(outputs.summary?.jsonError)
    || Boolean(outputs.store?.jsonError)
    || Boolean(outputs.store?.schemaError)
    || outputs.store?.filesReady === false;
}

function buildDoctorStorePerformance(store = {}) {
  return {
    ready: Boolean(store.exists && !store.jsonError && !store.schemaError && store.filesReady !== false),
    declaredFiles: store.declaredFiles ?? 0,
    filesReady: store.filesReady ?? null,
    missingFiles: store.missingFiles ?? [],
    totalBytes: store.totalBytes ?? null,
    totalJsonlRows: store.totalJsonlRows ?? null,
    jsonlTables: store.jsonlTables ?? 0,
    largestFiles: store.largestFiles ?? [],
    tables: store.tables ?? [],
  };
}

function buildDoctorCachePerformance(cache = {}) {
  const entries = Object.fromEntries(
    Object.entries(cache).map(([name, file]) => [
      name,
      {
        name,
        exists: Boolean(file.exists && file.type === "file"),
        bytes: file.exists && file.type === "file" ? file.bytes : null,
        modifiedAt: file.exists && file.type === "file" ? file.modifiedAt : null,
      },
    ]),
  );
  const files = Object.values(entries);
  const existing = files.filter((file) => file.exists && Number.isFinite(file.bytes));
  return {
    ready: existing.length === files.length && files.length > 0,
    files: entries,
    existingFiles: existing.length,
    totalFiles: files.length,
    totalBytes: existing.reduce((total, file) => total + file.bytes, 0),
    missing: files.filter((file) => !file.exists).map((file) => file.name),
  };
}

async function readDoctorRefreshHistory(refreshHistoryPath) {
  try {
    const items = JSON.parse(await readFile(refreshHistoryPath, "utf8"));
    if (!Array.isArray(items)) {
      return {
        items: [],
        warning: doctorRefreshHistoryWarning(
          "refresh_history_invalid_schema",
          "Refresh history must be an array and was ignored. Run a refresh to regenerate it.",
        ),
      };
    }
    return {
      items: normalizeDoctorRefreshHistory(items),
      warning: null,
    };
  } catch (error) {
    if (error.code === "ENOENT") return { items: [], warning: null };
    if (error instanceof SyntaxError) {
      return {
        items: [],
        warning: doctorRefreshHistoryWarning(
          "refresh_history_invalid_json",
          "Refresh history JSON is corrupt and was ignored. Run a refresh to regenerate it.",
        ),
      };
    }
    return {
      items: [],
      warning: doctorRefreshHistoryWarning(
        "refresh_history_unreadable",
        "Refresh history could not be read and was ignored.",
        { errorCode: error.code ?? null },
      ),
    };
  }
}

function doctorRefreshHistoryWarning(code, message, extra = {}) {
  return {
    code,
    message,
    ...extra,
  };
}

function normalizeDoctorRefreshHistory(items) {
  if (!Array.isArray(items)) return [];
  return items.map((item) => ({
    id: item.id ?? null,
    status: item.status ?? doctorRefreshStatus(item.phase),
    phase: item.phase ?? null,
    startedAt: item.startedAt ?? null,
    finishedAt: item.finishedAt ?? null,
    durationMs: Number.isFinite(item.durationMs) ? item.durationMs : durationBetweenMs(item.startedAt, item.finishedAt),
    phaseDurationsMs: item.phaseDurationsMs ?? phaseDurationsFromTimings(item.phaseTimings),
    errorCategory: item.errorCategory ?? null,
  }));
}

function publicDoctorRefreshHistoryItem(item) {
  if (!item) return null;
  return {
    id: item.id,
    status: item.status,
    phase: item.phase,
    startedAt: item.startedAt,
    finishedAt: item.finishedAt,
    durationMs: item.durationMs,
    phaseDurationsMs: item.phaseDurationsMs,
    errorCategory: item.errorCategory,
  };
}

function summarizeDoctorRefreshHistory(items) {
  const summary = {
    total: items.length,
    succeeded: 0,
    failed: 0,
    cancelled: 0,
    lastSucceededAt: null,
    lastErrorCategory: null,
    averageDurationMs: null,
    averagePhaseDurationsMs: {},
  };
  const durationValues = [];
  const phaseValues = {};
  for (const item of items) {
    if (item.status === "succeeded") {
      summary.succeeded += 1;
      summary.lastSucceededAt ??= item.finishedAt ?? null;
    } else if (item.status === "failed") {
      summary.failed += 1;
      summary.lastErrorCategory ??= item.errorCategory ?? null;
    } else if (item.status === "cancelled") {
      summary.cancelled += 1;
    }
    if (Number.isFinite(item.durationMs)) durationValues.push(item.durationMs);
    for (const [phase, durationMs] of Object.entries(item.phaseDurationsMs ?? {})) {
      if (!Number.isFinite(durationMs)) continue;
      phaseValues[phase] ??= [];
      phaseValues[phase].push(durationMs);
    }
  }
  summary.averageDurationMs = averageFinite(durationValues);
  summary.averagePhaseDurationsMs = Object.fromEntries(
    Object.keys(phaseValues)
      .sort()
      .map((phase) => [phase, averageFinite(phaseValues[phase])]),
  );
  return summary;
}

function buildDoctorPerformanceBaseline(items, warning = null) {
  const succeeded = items.filter((item) => item.status === "succeeded");
  const latestSucceeded = succeeded[0] ?? null;
  const phaseStats = summarizeDoctorPhaseDurations(succeeded);
  const bottleneckPhase = Object.values(phaseStats)
    .filter((item) => Number.isFinite(item.averageMs))
    .sort((a, b) => b.averageMs - a.averageMs || a.phase.localeCompare(b.phase))[0] ?? null;
  return {
    sampleSize: succeeded.length,
    latestSucceededAt: latestSucceeded?.finishedAt ?? null,
    latestDurationMs: latestSucceeded?.durationMs ?? null,
    averageDurationMs: averageFinite(succeeded.map((item) => item.durationMs)),
    phaseStats,
    bottleneckPhase,
    notes: succeeded.length
      ? [
          "Averages use successful refresh jobs only.",
          ...(warning ? [`Refresh history warning: ${warning.code}.`] : []),
        ]
      : [
          warning ? `Refresh history warning: ${warning.code}.` : "Run a successful refresh to collect a local performance baseline.",
        ],
  };
}

function buildDoctorPerformanceRecommendations({ baseline, store, cache, historyWarning, needsRefresh }) {
  const recommendations = [];
  if (historyWarning) {
    recommendations.push({
      code: "repair_refresh_history",
      severity: "info",
      message: "Run a refresh to regenerate the derived refresh-history baseline.",
      details: {
        warning: historyWarning.code,
      },
    });
  }
  if (needsRefresh) {
    recommendations.push({
      code: "refresh_needed",
      severity: "info",
      message: "Regenerate derived report and store outputs before judging backend performance.",
      details: {},
    });
  }
  if (!historyWarning && baseline.sampleSize === 0) {
    recommendations.push({
      code: "collect_refresh_baseline",
      severity: "info",
      message: "Run at least one successful refresh to collect local timing baselines.",
      details: {
        sampleSize: baseline.sampleSize,
      },
    });
  }
  const bottleneck = baseline.bottleneckPhase;
  if (bottleneck && Number.isFinite(bottleneck.averageMs) && bottleneck.averageMs >= 30000) {
    recommendations.push({
      code: "investigate_refresh_bottleneck",
      severity: "notice",
      message: "A refresh phase is slow enough to inspect before changing storage.",
      details: {
        phase: bottleneck.phase,
        averageMs: bottleneck.averageMs,
      },
    });
  }
  const storeBytes = Number.isFinite(store.totalBytes) ? store.totalBytes : 0;
  const storeRows = Number.isFinite(store.totalJsonlRows) ? store.totalJsonlRows : 0;
  if (storeBytes >= 250 * 1024 * 1024 || storeRows >= 1_000_000) {
    recommendations.push({
      code: "review_split_store_limits",
      severity: "notice",
      message: "The split JSONL store is large enough to review table-read latency before considering SQLite.",
      details: {
        totalBytes: store.totalBytes,
        totalJsonlRows: store.totalJsonlRows,
      },
    });
  }
  if (cache.totalFiles > 0 && cache.existingFiles < cache.totalFiles) {
    recommendations.push({
      code: "warm_missing_caches",
      severity: "info",
      message: "Run a refresh to rebuild missing derived cache files.",
      details: {
        existingFiles: cache.existingFiles,
        totalFiles: cache.totalFiles,
        missing: cache.missing,
      },
    });
  }
  if (!recommendations.length) {
    recommendations.push({
      code: "jsonl_store_ok",
      severity: "info",
      message: "Current split JSONL store and refresh baseline do not show a need for SQLite.",
      details: {
        sampleSize: baseline.sampleSize,
        totalBytes: store.totalBytes,
        totalJsonlRows: store.totalJsonlRows,
      },
    });
  }
  return recommendations;
}

function summarizeDoctorPhaseDurations(items) {
  const valuesByPhase = {};
  for (const item of items) {
    for (const [phase, durationMs] of Object.entries(item.phaseDurationsMs ?? {})) {
      if (!Number.isFinite(durationMs)) continue;
      valuesByPhase[phase] ??= [];
      valuesByPhase[phase].push(durationMs);
    }
  }
  return Object.fromEntries(
    Object.keys(valuesByPhase)
      .sort()
      .map((phase) => {
        const values = valuesByPhase[phase];
        return [
          phase,
          {
            phase,
            samples: values.length,
            averageMs: averageFinite(values),
            minMs: Math.min(...values),
            maxMs: Math.max(...values),
          },
        ];
      }),
  );
}

function doctorRefreshStatus(phase) {
  if (phase === "done") return "succeeded";
  if (phase === "cancelled") return "cancelled";
  if (phase === "failed") return "failed";
  return phase ? "running" : "idle";
}

function phaseDurationsFromTimings(phaseTimings = {}) {
  return Object.fromEntries(
    Object.entries(phaseTimings)
      .map(([phase, timing]) => [phase, Number.isFinite(timing?.durationMs) ? timing.durationMs : durationBetweenMs(timing?.startedAt, timing?.finishedAt)])
      .filter(([, durationMs]) => Number.isFinite(durationMs)),
  );
}

function durationBetweenMs(startedAt, finishedAt) {
  if (!startedAt || !finishedAt) return null;
  const started = Date.parse(startedAt);
  const finished = Date.parse(finishedAt);
  if (!Number.isFinite(started) || !Number.isFinite(finished)) return null;
  return Math.max(0, finished - started);
}

function averageFinite(values) {
  const finite = values.filter((value) => Number.isFinite(value));
  if (!finite.length) return null;
  return Math.round(finite.reduce((total, value) => total + value, 0) / finite.length);
}

function outputReady(output) {
  return Boolean(output.exists && !output.jsonError && !output.schemaError);
}

function validateStoreManifestForDoctor(manifest) {
  if (!manifest || typeof manifest !== "object" || Array.isArray(manifest)) return { ok: false, reason: "manifest_not_object", message: "Manifest must be a JSON object." };
  if (manifest.schema?.name !== "minecraft-log-observatory-store") return { ok: false, reason: "invalid_schema_name", message: "Manifest schema.name must be minecraft-log-observatory-store." };
  if (manifest.schema?.version !== 1) return { ok: false, reason: "invalid_schema_version", message: "Manifest schema.version must be 1." };
  if (!manifest.files || typeof manifest.files !== "object" || Array.isArray(manifest.files)) return { ok: false, reason: "missing_files", message: "Manifest files must be an object." };
  if (!manifest.counts || typeof manifest.counts !== "object" || Array.isArray(manifest.counts)) return { ok: false, reason: "missing_counts", message: "Manifest counts must be an object." };
  for (const [name, fileName] of Object.entries(manifest.files)) {
    if (!isSafeStoreManifestFileName(fileName)) return { ok: false, reason: "invalid_file", message: `Manifest files.${name} must be a safe relative file name.` };
  }
  return { ok: true };
}

function isSafeStoreManifestFileName(fileName) {
  if (typeof fileName !== "string" || !fileName) return false;
  if (fileName.includes("\0")) return false;
  if (path.isAbsolute(fileName) || path.posix.isAbsolute(fileName) || path.win32.isAbsolute(fileName)) return false;
  const normalized = path.posix.normalize(fileName.replace(/\\/g, "/"));
  return normalized !== "." && normalized !== ".." && !normalized.startsWith("../");
}

async function checkFile(filePath, options) {
  try {
    const fileStat = await stat(filePath);
    return {
      path: redactMaybe(filePath, options),
      exists: true,
      type: fileStat.isDirectory() ? "directory" : "file",
      bytes: fileStat.size,
      sizeMb: Number((fileStat.size / 1024 / 1024).toFixed(2)),
      modifiedAt: fileStat.mtime.toISOString(),
    };
  } catch (error) {
    if (error.code !== "ENOENT") throw error;
    return {
      path: redactMaybe(filePath, options),
      exists: false,
    };
  }
}

function isSameOrInside(child, parent) {
  const relative = path.relative(parent, child);
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

function redactMaybe(value, options) {
  if (options.full || !value) return value;
  return redactValue(value);
}

function redactList(values) {
  return values.map((value) => redactValue(String(value).trim().toLowerCase()));
}

function redactValue(value) {
  return {
    redacted: true,
    fingerprint: shortHash(String(value).toLowerCase()),
  };
}

function shortHash(value) {
  let hash = 2166136261;
  for (let index = 0; index < value.length; index += 1) {
    hash ^= value.charCodeAt(index);
    hash = Math.imul(hash, 16777619);
  }
  return (hash >>> 0).toString(16).padStart(8, "0");
}

function formatRedacted(value) {
  if (!value || typeof value !== "object") return value;
  return `[redacted:${value.fingerprint}]`;
}
