import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";

const contract = JSON.parse(await readFile("docs/openapi.json", "utf8"));

assert.equal(contract.openapi, "3.1.0");
assert.equal(contract.info.title, "Minecraft Log Observatory API");
assert.ok(contract.paths["/api/health"].get);
assert.ok(contract.paths["/api/app/status"].get);
assert.ok(contract.paths["/api/config"].get);
assert.ok(contract.paths["/api/config"].put);
assert.ok(contract.paths["/api/config"].put.responses["409"]);
assert.ok(contract.paths["/api/config/validate-roots"].post);
assert.ok(contract.paths["/api/system/select-directory"].post);
assert.equal(contract.paths["/api/system/select-directory"].post.requestBody.content["application/json"].schema.$ref, "#/components/schemas/SelectDirectoryRequest");
assert.equal(contract.paths["/api/system/select-directory"].post.responses["200"].content["application/json"].schema.$ref, "#/components/schemas/SelectDirectoryResponse");
assert.ok(contract.paths["/api/metrics/definitions"].get);
assert.match(contract.paths["/api/metrics/definitions"].get.summary, /metric definitions/);
assert.ok(contract.paths["/api/activity"].get);
assert.ok(contract.paths["/api/rounds"].get);
assert.match(contract.paths["/api/rounds"].get.summary, /server display fields/);
assert.ok(contract.paths["/api/rounds"].get.parameters
  .find((parameter) => parameter.name === "result")
  .schema.enum.includes("not_applicable"));
assert.ok(contract.paths["/api/rounds"].get.parameters.some((parameter) => parameter.name === "resultHintReason"));
assert.ok(contract.paths["/api/rounds"].get.parameters.some((parameter) => parameter.name === "unknownAuditCategory"));
assert.ok(contract.paths["/api/rounds"].get.parameters.some((parameter) => parameter.name === "unknownNextAction"));
assert.deepEqual(contract.paths["/api/rounds"].get.parameters.find((parameter) => parameter.name === "unknownReviewPriority").schema.enum, ["high", "medium", "low"]);
assert.ok(contract.paths["/api/result-candidates"].get);
assert.ok(contract.paths["/api/skin"].get);
assert.equal(contract.paths["/api/skin"].get.responses["200"].content["image/png"].schema.format, "binary");
assert.ok(contract.paths["/api/accounts/playtime"].get);
assert.ok(contract.paths["/api/refresh"].post);
assert.ok(contract.paths["/api/refresh/preflight"].post);
assert.ok(contract.paths["/api/refresh/cancel"].post);
assert.ok(contract.paths["/api/refresh/history"].get);
assert.ok(contract.paths["/api/data/cleanup"].post);
assert.ok(contract.paths["/api/diagnostics"].get);
assert.ok(contract.paths["/api/diagnostics"].get.responses["500"]);
assert.ok(contract.paths["/api/diagnostics/package"].get);
assert.match(contract.paths["/api/diagnostics/package"].get.summary, /without raw current files, errors, logs, or log tails/);
assert.ok(contract.paths["/api/share/package"].get);
assert.ok(contract.paths["/api/rules/test"].post);
assert.match(contract.paths["/api/rules"].get.summary, /rule quality summary/);
assert.ok(contract.paths["/api/rules/draft"].post);
assert.ok(contract.paths["/api/unknown-audit/labels"].post);
assert.equal(contract.paths["/api/unknown-audit/labels"].post.requestBody.content["application/json"].schema.$ref, "#/components/schemas/UnknownAuditLabelsRequest");
assert.equal(contract.paths["/api/unknown-audit/labels"].post.responses["200"].content["application/json"].schema.$ref, "#/components/schemas/UnknownAuditLabelsResponse");
assert.ok(contract.paths["/api/unknown-audit/label-sets"].get);
assert.ok(contract.paths["/api/unknown-audit/label-sets"].post);
assert.equal(contract.paths["/api/unknown-audit/label-sets"].post.requestBody.content["application/json"].schema.$ref, "#/components/schemas/UnknownAuditLabelSetSaveRequest");
assert.equal(contract.paths["/api/unknown-audit/label-sets"].post.responses["200"].content["application/json"].schema.$ref, "#/components/schemas/UnknownAuditLabelSetResponse");
assert.ok(contract.paths["/api/unknown-audit/label-sets/{id}"].get);
assert.ok(contract.paths["/api/unknown-audit/label-sets/{id}"].put);
assert.equal(contract.paths["/api/unknown-audit/label-sets/{id}"].put.requestBody.content["application/json"].schema.$ref, "#/components/schemas/UnknownAuditLabelSetUpdateRequest");
assert.ok(contract.paths["/api/unknown-audit/label-sets/{id}"].delete);
assert.ok(contract.paths["/api/rules/draft-from-labels"].post);
assert.equal(contract.paths["/api/rules/draft-from-labels"].post.requestBody.content["application/json"].schema.$ref, "#/components/schemas/RuleDraftFromLabelsRequest");
assert.ok(contract.paths["/api/rules/validate"].post);
assert.ok(contract.paths["/api/rules/doctor"].get);
assert.ok(contract.paths["/api/rules/audit"].get);
assert.ok(contract.paths["/api/rules/dry-run"].post);
assert.equal(contract.paths["/api/rules/dry-run"].post.requestBody.content["application/json"].schema.$ref, "#/components/schemas/RuleDryRunRequest");
assert.match(contract.paths["/api/rules/dry-run"].post.summary, /promotionGate/);
assert.ok(contract.paths["/api/rules/audit-workflow"].post);
assert.equal(contract.paths["/api/rules/audit-workflow"].post.requestBody.content["application/json"].schema.$ref, "#/components/schemas/RuleAuditWorkflowRequest");
assert.equal(contract.paths["/api/rules/audit-workflow"].post.responses["200"].content["application/json"].schema.$ref, "#/components/schemas/RuleAuditWorkflowResponse");
assert.match(contract.paths["/api/rules/audit-workflow"].post.summary, /draft rule pack/);
assert.ok(contract.paths["/api/rule-packs/user"].get);
assert.ok(contract.paths["/api/rule-packs/user"].post);
assert.ok(contract.paths["/api/rule-packs/user"].post.responses["409"]);
assert.ok(contract.paths["/api/rule-packs/user/enable"].post);
assert.ok(contract.paths["/api/rule-packs/user/backups"].post);
assert.ok(contract.paths["/api/rule-packs/user/restore"].post);
assert.ok(contract.paths["/api/rule-packs/user/{id}"].get);
assert.ok(contract.paths["/api/rule-packs/user/{id}"].delete);
assert.ok(contract.paths["/api/rule-packs/user/{id}"].delete.responses["409"]);
assert.ok(contract.paths["/api/store/table"].get);
assert.match(contract.paths["/api/results"].get.summary, /unknown audit queues/);
assert.match(contract.paths["/api/performance"].get.summary, /store read baseline/);
assert.match(contract.paths["/api/performance"].get.summary, /saved-baseline comparison/);
assert.match(contract.paths["/api/performance"].get.summary, /without raw refresh debug fields/);
assert.ok(contract.components.schemas.ConfigUpdateRequest);
assert.ok(contract.components.schemas.ValidateRootsRequest);
assert.deepEqual(contract.components.schemas.ValidateRootsRequest.required, ["roots"]);
assert.equal(contract.components.schemas.ValidateRootsRequest.additionalProperties, false);
assert.ok(contract.components.schemas.SelectDirectoryRequest.properties.validate);
assert.equal(contract.components.schemas.SelectDirectoryResponse.properties.validation.type, "object");
assert.ok(contract.components.schemas.CleanupRequest);
assert.equal(contract.components.schemas.CleanupRequest.properties.dryRun.type, "boolean");
assert.ok(contract.components.schemas.ServerEvidence);
assert.ok(contract.components.schemas.ServerEvidence.properties.source.enum.includes("chat_text"));
assert.ok(contract.components.schemas.RoundServerFields);
assert.deepEqual(contract.components.schemas.RoundServerFields.required, ["serverNetwork", "serverAddress", "serverLabel", "serverConfidence", "serverEvidence"]);
assert.ok(contract.components.schemas.RoundBedDestroyFields);
assert.deepEqual(contract.components.schemas.RoundBedDestroyFields.required, ["bedDestroys", "selfBedDestroys", "playerBedDestroys"]);
assert.match(contract.components.schemas.RoundBedDestroyFields.properties.playerBedDestroys.description, /equals selfBedDestroys/);
assert.ok(contract.components.schemas.RoundStreakFields);
assert.deepEqual(contract.components.schemas.RoundStreakFields.required, ["playerMaxKillStreak"]);
assert.match(contract.components.schemas.RoundStreakFields.properties.playerMaxKillStreak.description, /Broadcast streak messages/);
assert.ok(contract.components.schemas.WinStreakPolicySummary);
assert.deepEqual(contract.components.schemas.WinStreakPolicySummary.properties.policy.enum, ["break_unknown", "skip_unknown"]);
assert.ok(contract.components.schemas.ProfileStreaks);
assert.ok(contract.components.schemas.ProfileStreaks.properties.win.properties.breakUnknown);
assert.ok(contract.components.schemas.ProfileStreaks.properties.win.properties.skip_unknown);
assert.ok(contract.components.schemas.ActivityStreakFields);
assert.equal(contract.components.schemas.ActivityStreakFields.properties.maxStreak.deprecated, true);
assert.match(contract.components.schemas.ActivityStreakFields.properties.rewardEvents.description, /event count/);
assert.equal(contract.components.schemas.ActivityStreakFields.properties.goldEarned.type, "number");
assert.equal(contract.components.schemas.ActivityStreakFields.properties.xpEarned.type, "number");
assert.equal(contract.components.schemas.ActivityStreakFields.properties.bountyClaims.type, "integer");
assert.equal(contract.components.schemas.ActivityStreakFields.properties.bountyGoldEarned.type, "number");
assert.match(contract.components.schemas.ActivityStreakFields.properties.bountyGoldEarned.description, /included in goldEarned/);
assert.ok(contract.components.schemas.MetricDefinitions);
assert.equal(contract.components.schemas.MetricDefinition.properties.scope.type, "string");
assert.match(contract.components.schemas.MetricDefinitions.description, /observed broadcasts/);
assert.ok(contract.components.schemas.RulePack);
assert.ok(contract.components.schemas.RuleQualityRule.properties.rulePack);
assert.ok(contract.components.schemas.RuleQualitySummary.required.includes("byRulePack"));
assert.ok(contract.components.schemas.RuleQualitySummary.properties.byRulePack);
assert.ok(contract.components.schemas.RuleQualitySummary);
assert.ok(contract.components.schemas.RuleQualityRule);
assert.ok(contract.components.schemas.RuleQualityImpact);
assert.ok(contract.components.schemas.RuleQualityDuplicatePattern);
assert.ok(contract.components.schemas.RuleQualityRuleSetSummary);
assert.deepEqual(contract.components.schemas.RuleQualityRule.properties.riskGroup.enum, ["safe_result", "boundary_only", "diagnostic_only", "experimental"]);
assert.ok(contract.components.schemas.RuleQualitySummary.properties.resultImpactRules.items.$ref);
assert.ok(contract.components.schemas.RuleQualitySummary.properties.boundaryImpactRules.items.$ref);
assert.ok(contract.components.schemas.RuleDryRunRequest);
assert.ok(contract.components.schemas.RuleDryRunRequest.properties.targetMode);
assert.ok(contract.components.schemas.RuleDryRunPromotionGate);
assert.ok(contract.components.schemas.UnknownAuditLabelsRequest);
assert.equal(contract.components.schemas.UnknownAuditLabelsRequest.additionalProperties, false);
assert.ok(contract.components.schemas.UnknownAuditLabelsResponse);
assert.ok(contract.components.schemas.UnknownAuditLabelsResponse.required.includes("missingRuleTextRows"));
assert.equal(contract.components.schemas.UnknownAuditLabelsResponse.properties.missingRuleTextRows.items.$ref, "#/components/schemas/MissingRuleTextRow");
assert.ok(contract.components.schemas.UnknownAuditLabelSetSaveRequest);
assert.equal(contract.components.schemas.UnknownAuditLabelSetSaveRequest.additionalProperties, false);
assert.equal(contract.components.schemas.UnknownAuditLabelSetSaveRequest.properties.rows.items.$ref, "#/components/schemas/ReviewedLabelRow");
assert.ok(contract.components.schemas.UnknownAuditLabelSetUpdateRequest);
assert.equal(contract.components.schemas.UnknownAuditLabelSetUpdateRequest.additionalProperties, false);
assert.equal(contract.components.schemas.UnknownAuditLabelSetUpdateRequest.required, undefined);
assert.ok(contract.components.schemas.UnknownAuditLabelSetResponse);
assert.equal(contract.components.schemas.UnknownAuditLabelSetResponse.properties.writes.$ref, "#/components/schemas/UnknownAuditLabelSetWrites");
assert.equal(contract.components.schemas.UnknownAuditLabelSetWrites.properties.report.const, false);
assert.equal(contract.components.schemas.UnknownAuditLabelSetWrites.properties.store.const, false);
assert.equal(contract.components.schemas.UnknownAuditLabelSetWrites.properties.config.const, false);
assert.equal(contract.components.schemas.UnknownAuditLabelSetWrites.properties.rules.const, false);
assert.ok(contract.components.schemas.UnknownAuditLabelSetListResponse);
assert.ok(contract.components.schemas.UnknownAuditStatusResponse);
assert.ok(contract.components.schemas.UnknownAuditStatusResponse.required.includes("counts"));
assert.equal(contract.components.schemas.UnknownAuditStatusResponse.properties.counts.required.includes("missingRuleTextRows"), true);
assert.equal(contract.components.schemas.UnknownAuditLabelCandidates.properties.missingRuleTextRows.type, "integer");
assert.ok(contract.components.schemas.LabelReviewReadiness);
assert.ok(contract.components.schemas.LabelReviewReadinessStatus.enum.includes("ready_for_workflow"));
assert.ok(contract.components.schemas.LabelReviewReadinessStatus.enum.includes("needs_labeling"));
assert.equal(contract.components.schemas.LabelReviewReadiness.properties.status.$ref, "#/components/schemas/LabelReviewReadinessStatus");
assert.ok(contract.components.schemas.LabelReviewReadiness.required.includes("nextStep"));
assert.ok(contract.components.schemas.LabelReviewReadiness.required.includes("blocked"));
assert.ok(contract.components.schemas.LabelReviewReadiness.required.includes("canRunDryRun"));
assert.ok(contract.components.schemas.LabelReviewReadiness.properties.nextStep.enum.includes("run_audit_workflow"));
assert.ok(contract.components.schemas.LabelReviewReadiness.properties.nextStep.enum.includes("archive_keep_unknown"));
assert.equal(contract.components.schemas.UnknownAuditLabelsResponse.properties.readiness.$ref, "#/components/schemas/LabelReviewReadiness");
assert.ok(contract.components.schemas.UnknownAuditLabelsResponse.properties.readyForWorkflow);
assert.ok(contract.components.schemas.UnknownAuditLabelsResponse.properties.workflowRecommended);
assert.ok(contract.components.schemas.RuleDraftFromLabelsRequest.properties.validateRoundRefs);
assert.ok(contract.components.schemas.RuleAuditWorkflowRequest.properties.skipDryRun);
assert.ok(contract.components.schemas.RuleAuditWorkflowResponse);
assert.ok(contract.components.schemas.RuleAuditWorkflowResponse.required.includes("workflow"));
assert.equal(contract.components.schemas.RuleAuditWorkflowResponse.properties.artifactSummary.$ref, "#/components/schemas/AuditWorkflowArtifactSummary");
assert.equal(contract.components.schemas.AuditWorkflowArtifactSummary.properties.privacy.const, "local_paths_redacted");
assert.ok(contract.components.schemas.AuditWorkflowStatus.properties.status.enum.includes("missing_rule_text"));
assert.ok(contract.components.schemas.AuditWorkflowStatus.properties.status.enum.includes("dry_run_review"));
assert.equal(contract.components.schemas.NoOfficialWrites.properties.report.const, false);
assert.equal(contract.components.schemas.NoOfficialWrites.properties.labelSet.const, false);
assert.equal(contract.components.schemas.AuditWorkflowWrites.properties.dryRunCache.type, "boolean");
assert.ok(contract.components.schemas.ReviewedLabelRow.properties.reviewLabel.enum.includes("new-rule-needed"));
assert.ok(contract.components.schemas.PerformanceComparison);
assert.ok(contract.components.schemas.ApiEnvelope);
assert.ok(contract.components.schemas.ApiEnvelope.properties.ok);
assert.ok(contract.components.schemas.ApiEnvelope.properties.error);
assert.ok(contract.components.schemas.ApiEnvelope.properties.message);

console.log("openapi tests passed");
